### ISSUE TITLE
Crash: cannot read dependency_name of null

### ISSUE THREAD

**Issue by AlCalzone** [ahmadnassri/action-dependabot-auto-merge#26]
https://github.com/ioBroker/create-adapter/pull/593/checks?check_run_id=1191533085
Is there a way to pin actions to a specific version instead of just @v2 in order to avoid such issues in the future?

Log output:
```
loaded merge config: 
- match:
  dependency_type: development
  update_type: "semver:minor"
- match:
  dependency_type: production
  update_type: "security:minor"
- match:
  dependency_type: production
  update_type: "semver:patch"

title: "chore(deps-dev): bump @types/eslint from 7.2.2 to 7.2.3"
depName: @types/eslint
from: 7.2.2
to: 7.2.3
dependency type: development
security critical: false
Error: Cannot read property 'dependency_name' of null
TypeError: Cannot read property 'dependency_name' of null
    at default (file:///action/lib/parse.js:85:25)
    at default (file:///action/lib/index.js:20:19)
    at file:///action/index.js:51:7
    at ModuleJob.run (internal/modules/esm/module_job.js:140:23)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

**Comment by AlCalzone** [comment]
Nevermind, the auto-merge.yml is formatted badly. There are two spaces missing in front of `dependency_type` and `update_type`.

**Comment by ahmadnassri** [comment]
nevertheless, we should catch that error and produce a better message.
