### ISSUE TITLE
TypeError: Cannot read property 'dependency_name' of null

### ISSUE THREAD

**Issue by bedrockcoder** [ahmadnassri/action-dependabot-auto-merge#49]
[The run](https://github.com/bedrockcoder/convert-to-string/runs/1648390938)  
[The workflow file](https://github.com/bedrockcoder/convert-to-string/blob/33bbc789e759b6d7eb0cfc2af6d4f9c5f2498ece/.github/workflows/auto-merge.yml)  
The error:
```
Error: Cannot read property 'dependency_name' of null
TypeError: Cannot read property 'dependency_name' of null
    at default (file:///action/lib/parse.js:94:25)
    at default (file:///action/lib/index.js:20:19)
    at file:///action/index.js:52:7
    at ModuleJob.run (node:internal/modules/esm/module_job:152:23)
    at async Loader.import (node:internal/modules/esm/loader:166:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
```

**Comment by AraHaan** [comment]
Duplicate of #26?

**Comment by bedrockcoder** [comment]
I think it is, thanks!
